name: Test

on:
  push:

jobs:

  test:
    name: Test
    strategy:
      matrix:
        LETTER: [ "a", "b" ]
    runs-on: ubuntu-22.04
    steps:

    - name: Install uniget
      uses: uniget-org/uniget-action@main
      with:
        prefix: helper
        tools: gojq regclient

    - name: Debug
      run: |
        printenv | sort

    - name: Collect
      id: collect
      run: |
        echo "Filter: ${LETTER}"
        helper/usr/local/bin/regctl manifest get ghcr.io/uniget-org/tools/metadata:main --format raw-body \
        | helper/usr/local/bin/jq --raw-output '.layers[0].digest' \
        | xargs -I{} \
            helper/usr/local/bin/regctl blob get ghcr.io/uniget-org/tools/metadata:main {} \
        | tar --extract --gzip --to-stdout \
        | helper/usr/local/bin/jq --raw-output --arg prefix "${LETTER}" '.tools[] | select(.name | startswith($prefix)) | "\(.name):\(.version)"'
