name: Test

on:
  push:

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        LETTER: [ "a", "b" ]
    steps:

    - name: Test
      run: |
        echo "Test: ${LETTER}, ${QUEUE}."
