name: Test

on:
  push:

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
        - LETTER: a
          QUEUE: [ "1", "2", "3" ]
        - LETTER: b
          QUEUE: [ "4", "5", "6" ]
    steps:

    - name: Test
      run: |
        echo "Test: ${LETTER}, ${QUEUE}."
